config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :playlists, only: [:show, :update, :destroy] do
    member do
      get :items
    end
  end
  resource :search, only: [:create]
  resources :channels, only: [:show]
  resource :account, only: [:show]
  
  get 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  get 'joke' => 'pages#joke', as: :joke
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'privacy' => 'pages#privacy', as: :privacy
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/views/pages/about.html.slim
- title "About"

.hero.about
  .container.text-center.text-light
    .row  
      .col
        h1 About PlaybackLoop

.container.blog
  .row.my-4
    .col
      h4 Really? There is no way to play a Youtube playlist by oldest videos first?!
      p 
        | I like to watch stuff while I work on my computer. I found this 
        = link_to 'playlist of Intro Monologues from The Late Show With Steven Colbert', 'https://www.youtube.com/playlist?list=PLiZxWe0ejyv8CSMylrxb6Nx4Ii2RHbu_j'
        |  and started watching.  Good stuff!  They keep adding to the playlist and put the new stuff on top, so as I was watching it, I was watching it in reverse chronological order!
      p
        | So after a quick google search, I found out I cannot change the order unless I own the playlist or copy it.  I don't wanna spend my time doing that! So instead I spent an even longer time making this website so I can watch videos as God intended, in order with the oldest first!
      p
        | I hope other people find this useful. Also if I have more time and resources, I would like to add more features on this site.  My long term goal is to emulate this old favorite technology called TV.  Contact me at info@playbackloop.com with feedback or comments. Cheers! 🍻
      

app/views/pages/index.html.slim
- title 'Watch Youtube Playlists and Channels In Chronological Order'

.article.py-5.bg-gradient-primary.text-white
  .container-fluid.py-5
    .row.text-center
      .col
        h1.h2 Watch Youtube Playlists in Chronological Order
        = form_with url: search_path, local: true do
          .row
            .offset-lg-3.col-lg-5.col-md-9.pr-md-0
              .form-group
                = text_field_tag :query, nil, placeholder: 'Youtube Playlist or Channel URL', class: 'form-control form-control-lg', required: true
            .col-md-3.col-lg-1
              = button_tag class: 'btn btn-warning btn-lg text-white', data: { disable_with: '...' }, style: 'width: 100%', name: nil do
                = fa_icon 'search'

.article.py-5
  .container
    .row.text-center
      .col-sm-4.mb-2
        = fa_icon 'sort-amount-asc 3x', class: 'mb-3'
        h3 Watch In Order
        p Watch Youtube playlists in order from oldest to newest, as it should be.
      .col-sm-4.mb-2
        = fa_icon 'arrows-alt 3x', class: 'mb-3'
        h3 Resize The Player
        p Resize your browser window to change player size for background watching.
      .col-sm-4.mb-2
        = fa_icon 'user-circle 3x', class: 'mb-3'
        h3 Watch Your Playlists
        p Connect your Youtube to access catch up on your subscriptions and playlists.

= render 'playlists/list_cards', playlists: @current_playlists, headline: 'Recently Watched By You', removable: true
= render 'playlists/list_cards', playlists: @recent_playlists, headline: 'Recently Watched By Others'

app/views/pages/joke.html.slim
.alert.alert-info
  .row
    .col
      .joke-title.small.mb-2
        | Jokes for Donations 
        = link_to 'What is this?', blog_path(slug: 'i-work-hard-so-my-cat-can-have-a-better-life'), class: 'small float-right', target: '_blank'
      = @joke
    .col-xs-auto
      = image_tag 'venmo_me3.png', style: 'height: 100px;'

app/views/pages/privacy.html.slim
- title "Privacy Policy"

.hero
  .container.text-center.text-light
    .row  
      .col
        h1 Privacy Policy

.container
  .row.my-4
    .col
      p
        | Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
      ul
        li
          | Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
        li
          | We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.
        li
          | We will only retain personal information as long as necessary for the fulfillment of those purposes.
        li
          | We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.
        li
          | Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
        li
          | We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
        li
          | We will make readily available to customers information about our policies and practices relating to the management of personal information.
      p
        | We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.

      hr
      p
        | This privacy policy has been compiled to better serve those who are concerned with how their 'Personally Identifiable Information' (PII) is being used online. PII, as described in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.

      h5 What personal information do we collect from the people that visit our blog, website or app?
      p When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address or other details to help you with your experience.

      h5 When do we collect information?
      p We collect information from you when you register on our site or enter information on our site.

      h5 How do we use your information?
      p
        | We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:

      ul
        li To personalize your experience and to allow us to deliver the type of content and product offerings in which you are most interested.
        li To improve our website in order to better serve you.
        li To administer a contest, promotion, survey or other site feature.
        li To ask for ratings and reviews of services or products

      h5 How do we protect your information?
      p We only provide articles and information. We never ask for credit card numbers.
      p Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.
      p We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety of your personal information.
      p All transactions are processed through a gateway provider and are not stored or processed on our servers.

      h5 Do we use 'cookies'?
      p Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.

      h5 We use cookies to:
      ul
        li Understand and save user's preferences for future visits.
        li Keep track of advertisements.
        li Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third-party services that track this information on our behalf.

        p You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since browser is a little different, look at your browser's Help Menu to learn the correct way to modify your cookies.

      h5 If users disable cookies in their browser:
      p If you turn cookies off, Some of the features that make your site experience more efficient may not function properly.Some of the features that make your site experience more efficient and may not function properly.

      h5 Third-party disclosure
      p We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information unless we provide users with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential. We may also release information when it's release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property or safety.
      p However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.

      h5 Third-party links
      p Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

      h5 Google
      p Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. 
      = link_to 'https://support.google.com/adwordspolicy/answer/1316548?hl=en'

      p We use Google AdSense Advertising on our website.
      p Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.

      h5 We have implemented the following:
      ul
        li Remarketing with Google AdSense
        li Google Display Network Impression Reporting
        li Demographics and Interests Reporting

      p We, along with third-party vendors such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website.

      h5 Opting out:
      p Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising Initiative Opt Out page or by using the Google Analytics Opt Out Browser add on.

      h5 California Online Privacy Protection Act
      p CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy.  The law's reach stretches well beyond California to require any person or company in the United States (and conceivably the world) that operates websites collecting Personally Identifiable Information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared. -  See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf
        
      h5 According to CalOPPA, we agree to the following:

      p Users can visit our site anonymously.
      p Once this privacy policy is created, we will add a link to it on our home page or as a minimum, on the first significant page after entering our website.
      p Our Privacy Policy link includes the word 'Privacy' and can easily be found on the page specified above.

      p You will be notified of any Privacy Policy changes:
      ul
        li On our Privacy Policy Page

      p Can change your personal information:
      ul
        li By logging in to your account

      h5 How does our site handle Do Not Track signals?
      p We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.

      h5 Does our site allow third-party behavioral tracking?
      p  It's also important to note that we allow third-party behavioral tracking

      h5 COPPA (Children Online Privacy Protection Act)
      p When it comes to the collection of personal information from children under the age of 13 years old, the Children's Online Privacy Protection Act (COPPA) puts parents in control.  The Federal Trade Commission, United States' consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.
      p We do not specifically market to children under the age of 13 years old.
      p Do we let third-parties, including ad networks or plug-ins collect PII from children under 13?

      h5 Fair Information Practices
      p The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.

      h5 In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:
      p We will notify you via email and we will notify the users via in-site notification
      p We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.

      h5 CAN SPAM Act
      p The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.
          
      p We collect your email address in order to:
      ul
        li Send information, respond to inquiries, and/or other requests or questions

      p To be in accordance with CANSPAM, we agree to the following:
      ul
        li Not use false or misleading subjects or email addresses.
        li Identify the message as an advertisement in some reasonable way.
        li Include the physical address of our business or site headquarters.
        li Monitor third-party email marketing services for compliance, if one is used.
        li Honor opt-out/unsubscribe requests quickly.
        li Allow users to unsubscribe by using the link at the bottom of each email.
      p 
        | If at any time you would like to unsubscribe from receiving future emails, you can ollow the instructions at the bottom of each email and we will promptly remove you from
        strong ALL
        | marketing correspondence.

      h5 Contacting Us
      p If there are any questions regarding this privacy policy, you may contact us at info@#{app_name}.com
      p Last Edited on 2017-10-14

app/views/pages/terms.html.slim
- title "Terms & Conditions"

.hero
  .container.text-center.text-light
    .row  
      .col
        h1 Terms and Conditions

.container.blog
  .row.my-4
    .col
      h4
        | 1. Terms
      p
        | By accessing this web site, you are agreeing to be bound by these web site Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this web site are protected by applicable copyright and trade mark law.
      h4
        | 2. Use License
      ol type="a"
        li
          | Permission is granted to temporarily download one copy of the materials
          |  (information or software) on #{app_name}'s web site for personal,
          |  non-commercial transitory viewing only. This is the grant of a license,
          |  not a transfer of title, and under this license you may not:
          ol type="i"
            li modify or copy the materials;
            li use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
            li attempt to decompile or reverse engineer any software contained on #{app_name}'s web site;
            li remove any copyright or other proprietary notations from the materials; or
            li transfer the materials to another person or "mirror" the materials on any other server.
        li
          | This license shall automatically terminate if you violate any of these restrictions and may be terminated by #{app_name} at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
      h4
        | 3. Disclaimer
      ol type="a"
        li
          | The materials on #{app_name}'s web site are provided "as is". #{app_name} makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, #{app_name} does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
      h4
        | 4. Limitations
      p
        | In no event shall #{app_name} or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on #{app_name}'s Internet site, even if #{app_name} or a #{app_name} authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
      h4
        | 5. Revisions and Errata
      p
        | The materials appearing on #{app_name}'s web site could include technical, typographical, or photographic errors. #{app_name} does not warrant that any of the materials on its web site are accurate, complete, or current. #{app_name} may make changes to the materials contained on its web site at any time without notice. #{app_name} does not, however, make any commitment to update the materials.
      h4
        | 6. Links
      p
        | #{app_name} has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by #{app_name} of the site. Use of any such linked web site is at the user's own risk.
      h4
        | 7. Site Terms of Use Modifications
      p
        | #{app_name} may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
      h4
        | 8. Governing Law
      p
        | Any claim relating to #{app_name}'s web site shall be governed by the laws of the State of California without regard to its conflict of law provisions.
      p
        | General Terms and Conditions applicable to Use of a Web Site.