config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :playlists, only: [:show, :update, :destroy] do
    member do
      get :items
    end
  end
  resource :search, only: [:create]
  resources :channels, only: [:show]
  resource :account, only: [:show]
  
  get 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  get 'joke' => 'pages#joke', as: :joke
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'privacy' => 'pages#privacy', as: :privacy
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/models/playlist.rb
class Playlist
  attr_accessor :service, :playlist_id, :items, :max_results, :page_token, :title, :total

  MAX_LOAD = 1500

  def initialize(service, playlist_id)
    @service = service
    @playlist_id = playlist_id
    @items = []
    @page_token = nil
    @max_results = 50
  end

  def load_playlist
    begin
      list = service.list_playlist_items(list_playlist_items_parts,
        playlist_id: playlist_id,
        max_results: max_results,
        page_token: page_token)
        #fields: list_playlist_items_fields)
      @items += list.items
      @page_token = list.next_page_token
    end while page_token.present? && @items.count < MAX_LOAD
    @items.reject! { |i| i.content_details.video_published_at.nil? }
  end

  def youtube_playlist
    @youtube_playlist ||= begin
      yp = YoutubePlaylist.find_by(youtube_id: playlist_id)
      if yp&.refreshed?
        yp
      else
        list = YoutubePlaylistFetcher.new(service, ids: playlist_id).fetch
        YoutubePlaylistImporter.new(list.items.first).import!
      end
    end
  end

  # need to create a Playlist::Sort class
  def sorted_items(sort_order = :date_asc)
    case sort_order.to_sym
    when :date_asc
      items.sort { |x,y| x.content_details.video_published_at <=> y.content_details.video_published_at }
    when :date_desc
      items.sort { |x,y| y.content_details.video_published_at <=> x.content_details.video_published_at }
    when :position_desc
      items.reverse
    when :title
      items.sort { |x,y| x.snippet.title <=> y.snippet.title }
    else # :position_asc
      items
    end
  end

  private

  def list_playlist_items_parts
    'contentDetails,snippet'
  end

  def list_playlist_items_fields
    'kind,next_page_token,page_info,prev_page_token,items(snippet(title,description,thumbnails/medium,position),contentDetails)'
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :sync_to_cookies, only: :show
  before_action :set_sort_order, only: [:show, :items]
  after_action :cache_playlists_views

  def show
    @playlist = Playlist.new(@ys, params[:id])
    begin
      @youtube_playlist = @playlist.youtube_playlist
    rescue Google::Apis::ClientError => e
      return playlist_not_found
    rescue Exception => e
      return playlist_not_found
    end
  end

  def update
    return unless current_user
    view = current_user.views.playlist.where(list_id: params[:id]).first_or_create
    view.update(video_id: params[:video_id], sort_order: params[:sort_order], deleted_at: nil)
    head :ok
  end

  def items
    return head(:ok) if browser.bot?

    @playlist = Playlist.new(@ys, params[:id])
    begin
      @playlist.load_playlist
    rescue Google::Apis::ClientError => e
      return playlist_not_found
    rescue Exception => e
      return playlist_not_found
    end
    items = @playlist.sorted_items(@sort_order)
    render 'playlists/_playlist', locals: { items: items, playing: items.first }, layout: false
  end

  def destroy
    return unless current_user
    @view = current_user.views.playlist.find_by_list_id params[:id]
    if @view
      @view.deleted_at ||= Time.current
      @view.save
    end
  end

  private

  def playlist_not_found
    redirect_to root_path, alert: 'Could not find the Playlist'
  end

  def cache_playlists_views
    updated_playlists = recent_playlists_cache.unshift(params[:id]).uniq.slice(0,100)
    Rails.cache.write('recent_playlists', updated_playlists)
  end

  def set_sort_order
    @sort_order = params[:sort] || last_view_sort || cookie_sort || :date_asc
  end

  def last_view_sort
    current_user.views.playlist.where(list_id: params[:id]).first.try(:sort_order) if current_user
  end

  def cookie_sort
    cookie_playlist_views[params[:id]].try(:last)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def sort_order_options(active = nil)
    options = [
      ['Oldest First', :date_asc],
      ['Newest First', :date_desc],
      ['Playlist Order', :position_asc],
      ['Title', :title]
    ]
    options_for_select(options, active)
  end
  
  def sleep_timer_options
    {
      '15 Mins' => 15 * 60,
      '30 Mins' => 30 * 60,
      '45 Mins' => 45 * 60,
      '1 Hour' => 60 * 60,
      '1.5 Hour' => 90 * 60
    }
  end
end

app/views/playlists/_card.html.slim
- snippet = item.snippet
- thumbnail_url = (snippet.thumbnails.high || snippet.thumbnails.standard).try(:url)
- removable ||= false

.playlist-card.card.mb-2 id=("pid-#{item.id}")
  - if removable
    = link_to playlist_path(id: item.id), class: 'remove badge badge-dark', method: :delete, remote: true do
      = fa_icon 'trash'
  a href=playlist_path(id: item.id)
    img.card-img-top.img-fluid src=thumbnail_url alt="#{snippet.title} by #{snippet.channel_title}"
    .count.badge.badge-light alt="#{pluralize item.content_details&.item_count, 'Video'}"
      = item.content_details&.item_count
  .card-body
    = snippet.title
    small
      |  - #{snippet.channel_title}

app/views/playlists/_list_cards.html.slim
- removable ||= false
- if playlists.present?
  .article.py-4
    .container-fluid
      .row
        .col
          h4.hr= headline
      .row
        - playlists.each do |p|
          .col-6.col-sm-4.col-lg-3.col-xl-2= render 'playlists/card', item: p, removable: removable

app/views/playlists/_load_videos.html.slim
javascript:
  payload = #{raw items.map(&:to_json)};
  playlist_id = '#{@playlist.playlist_id}';
  sort_order = '#{@sort_order}';

coffee:
  # async load iframe api
  tag = document.createElement('script')
  tag.src = 'https://www.youtube.com/iframe_api'
  firstScriptTag = document.getElementsByTagName('script')[0]
  firstScriptTag.parentNode.insertBefore tag, firstScriptTag

  window.onYouTubeIframeAPIReady = ->
    videos = payload.map(JSON.parse)
    window.playlist = new Playlist(items: videos)
    window.player = new (YT.Player)(
      'player',
      events:
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange)
    return

  onPlayerReady = (event) ->
    last_video = lastPlayedVid()
    if last_video
      position = playlist.positionByVid(last_video)
      $('#playlist-wrapper').animate({ scrollTop: $("#vid_#{last_video}").offset().top - 60 }, 'slow')
    else
      position = 0
    playlist.playVideo(position)
    

  onPlayerStateChange = (event) ->
    if event.data == -1 # unstarted / new vid
      video_id = player.getVideoData().video_id
      playlist.setPosition(video_id)
      updateCookie(video_id)
      playlist.updatePosition(video_id)

  updateCookie = (video_id) ->
    h = {}
    h[playlist_id] = [video_id, sort_order]
    playlists = Cookies.getJSON('playlists')
    playlists = $.extend(playlists, h)
    keys = Object.keys(playlists)
    # keep last 30 to prevent cookie overflow
    key_to_delete = keys.slice(0, Math.max(keys.length - 30, 0))
    $.each(key_to_delete, (i, val) => delete playlists[val])
    Cookies.set('playlists', playlists, { expires: 365 })

  lastPlayedVid = ->
    cookie = Cookies.getJSON('playlists')
    cookie[playlist_id][0] if cookie && cookie[playlist_id] && (cookie[playlist_id][1] == sort_order)

app/views/playlists/_playlist.html.slim
- if items.count >= Playlist::MAX_LOAD
  .alert.alert-warning This playlist is huge and only the latest #{Playlist::MAX_LOAD} videos were loaded.
.list-group
  = render partial: 'playlist_item', collection: items, locals: { total_count: items.count, playing: playing }

= render 'load_videos', items: items
javascript:
  var myLazyLoad = new LazyLoad({ container: document.getElementById('playlist-wrapper') });

app/views/playlists/_playlist_item.html.slim
- video_id = playlist_item.content_details.video_id
- classes = ['list-group-item', 'list-group-item-action', 'playlist-item', 'rounded-0']
- classes << 'active' if playlist_item == playing
- data = { position: playlist_item_counter, vid: video_id }

a href=url_for(anchor: video_id) data=data class=classes.join(' ') id="vid_#{video_id}"
  .infobar
    .thumb
      img data-src=playlist_item.snippet.thumbnails.medium.url alt='thumb' width='100' height='56'
    .position.badge.badge-secondary
      | #{playlist_item.snippet.position + 1} / #{total_count}
  .title
    strong= playlist_item.snippet.title
  .published_at= local_time(playlist_item.content_details.video_published_at, :date_only)

app/views/playlists/destroy.js.erb
// hide item
$(".playlist-card#pid-<%= params[:id] %>").parent().slideToggle();

// remove from cookie
cookie = Cookies.getJSON('playlists');
delete cookie['<%= params[:id] %>'];
Cookies.set('playlists', cookie, { expires: 365 });

app/views/playlists/show.html.slim
- title "#{@youtube_playlist.title} - #{@youtube_playlist.channel_title}"
- meta_desc "#{@youtube_playlist.description}"

.container-fluid
  #playlist-player.row
    #now-playing.mt-2
      .row
        .col
          h1.h5.playlist-title alt=@youtube_playlist.description
            = @youtube_playlist.title
            em.small
              |  by 
              = link_to @youtube_playlist.channel_title, "https://www.youtube.com/channel/#{@youtube_playlist.youtube_channel_id}", target: '_blank'

        .col-md-auto.mb-2
          #play-actions.float-right
            #sort-menu
              = select_tag :sort_order, sort_order_options(@sort_order), id: 'sort-menu-select', data: { playlist_id: params[:id] }
            #view-mode.d-none.d-md-inline-block
              button#view-mode-toggle.btn.btn-tiny.btn-dark title='Theater Mode'
                = fa_icon 'arrows-h'
            #dark-mode
              button#dark-mode-toggle.btn.btn-tiny.btn-secondary title='Dark Mode'
                = fa_icon 'adjust'
            #sleep-timer
              #sleep-timer-dropdown.dropdown
                button#sleep-timer-button.btn.btn-dark.btn-tiny.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  = fa_icon 'hourglass-half'
                .dropdown-menu.dropdown-menu-right aria-labelledby="dropdownMenuButton" style="min-width: auto;"
                  a.dropdown-item.stop-timer href='#' data-value=0 style='display: none' Stop
                  - if Rails.env.development?
                    a.dropdown-item href='#' data-value=5 5 seconds
                  - sleep_timer_options.each do |text, secs|
                    a.dropdown-item href='#' data-value=secs
                      = text

      .player-wrapper
        iframe#player allowfullscreen='1' type="text/html" width="640" height="390" src==("https://www.youtube.com/embed/xxxxx?enablejsapi=1&origin=#{CGI.escape(root_url.chomp('/'))}&rel=0") frameborder="0"
      h5.title.mt-2.mb-0
      hr.mt-0
      .description
        pre
      #begging_with_jokes

    #playlist-wrapper
      #playlist-items
        .text-center.pt-4
          = fa_icon 'circle-o-notch spin 3x'
      - content_for :inline_js
        javascript:
          $(function() {
            $("#playlist-items").load("#{items_playlist_path(id: @playlist.playlist_id, sort: @sort_order)}");
          });