config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :playlists, only: [:show, :update, :destroy] do
    member do
      get :items
    end
  end
  resource :search, only: [:create]
  resources :channels, only: [:show]
  resource :account, only: [:show]
  
  get 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  get 'joke' => 'pages#joke', as: :joke
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'privacy' => 'pages#privacy', as: :privacy
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/views/layouts/_flashes.html.slim
- flash.each do |k,v|
  .alert.alert-dismissible.fade.show.mb-0 class=alert_helper(k) role="alert"
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" &times;
    = v

coffee:
  setTimeout (-> $('#flashes .alert [data-dismiss="alert"]').click()), 3000

app/views/layouts/_footer.html.slim
footer.footer.bg-dark
  .container
    .row
      .col-lg.text-center.text-lg-left.mt-lg-3
        = link_to 'About', about_path, class: 'mr-4 text-light'
        = link_to 'Blog', blogs_path, class: 'mr-4 text-light'
        = link_to 'Terms', terms_path, class: 'mr-4 text-light'
        = link_to 'Privacy', privacy_path, class: 'mr-4 text-light'
      .col-lg.text-center.text-lg-right.mt-lg-3
        span.text-muted Copyright © #{Time.current.year} #{app_name}, All Rights Reserved

app/views/layouts/_nav_bar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.sticky-top
  a.navbar-brand href=root_path
    == app_logo
  .navbar-right
    - if logged_in?
      a.d-lg-none.account href=account_path
        img src=current_user.avatar_url style='width: 32px'
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
    - if logged_in?
      a.d-none.d-lg-block.account href=account_path
        img src=current_user.avatar_url style='width: 32px'
    ul.navbar-nav
      - if logged_in?
        li.nav-item
          a.nav-link href=logout_path Logout
      - else
        li.nav-item
          a.nav-link href=login_path Connect

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title= content_for?(:title) ? yield(:title) : app_name
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    - if content_for?(:canonical)
      link rel='canonical' href=yield(:canonical)
    - if content_for?(:robots)
      meta name='robots' content=yield(:robots)
    - if content_for?(:meta_desc)
      meta name='description' content=yield(:meta_desc)
    = csrf_meta_tag
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Josefin+Sans|Roboto'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = render 'layouts/google_analytics' if Rails.env.production?
    
    link rel='apple-touch-icon' sizes='128x128' href=image_url('icon_128x128.png')
    link rel='apple-touch-icon' sizes='256x256' href=image_url('icon_256x256.png')
    link rel='icon' type='image/png' href=image_url('icon_32x32.png')
  body
    = render 'layouts/nav_bar'
    #flashes= render 'layouts/flashes'
    = yield
    = render 'layouts/footer'

    script data-turbolinks-eval='false' src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" crossorigin="anonymous"
    = javascript_include_tag 'application', 'data-turbolinks-eval': 'false'
    = yield(:inline_js) if content_for?(:inline_js) 